### ISSUE TITLE
App Insights not working with 6.0.0.53 by default

### ISSUE THREAD

**Issue by marmy28** [junalmeida/autofac-azurefunctions#10]
Before using this package my azure functions were logging to app insights by default. I noticed it stopped around the time I started using this package. I was able to get my default app insights logging to occur again once I downgraded to 6.0.0.51. Am I supposed to do something extra with 6.0.0.53 to get app insights to work?

Thank you for your time.

**Comment by junalmeida** [comment]
Not that I am aware @marmy28. Is your az function service configured to app insights via those two settings? 
![image](https://user-images.githubusercontent.com/991675/105411205-b7498d80-5bf8-11eb-89c4-e64be3523a3a.png)

**Comment by marmy28** [comment]
I just have APPINSIGHTS_INSTRUMENTATIONKEY with the guid value. I am using v3 azure functions with netcore 3.1.

**Comment by Callindrill** [comment]
Can confirm that this was also the case for us. Downgrading to 6.0.0.51 resolved the issue. When using 6.0.0.53 we were not seeing anything logging in app insights anymore, though we COULD see these logged if we connected to the log stream and watched that live.

**Comment by MohadKamil** [comment]
This is also the issue for me, I can see in my logs this entry:
"AI: Process was called on the TelemetrySink after it was disposed, the telemetry data was dropped."

Inspecting the Logger Module, TelemetryClient is registered as PerTriggeredRequest and I'm assuming the container disposes of the TelemetryClient before the collected telemetry is pushed

**Comment by junalmeida** [comment]
Since this is an issue for most, myself included, I will be for now removing support on `TelemetryClient` and also removing that dependency (less dependencies, better). 

If you still want to have the Telemetry Client you can register it in Autofac Configuration method during startup.

**Comment by junalmeida** [comment]
@marmy28 , @MohadKamil , @Callindrill 
Please if possible test out the new version (check latest releases), it is now possible to reference `TelemetryClient` in a service or function class.

**Comment by marmy28** [comment]
This does seem to be working for me now, thank you for your time!
