### ISSUE TITLE
Can you add support/extension to register multitenant container

### ISSUE THREAD

**Issue by ssunkari** [junalmeida/autofac-azurefunctions#18]
https://autofac.readthedocs.io/en/latest/advanced/multitenant.html
Below is the config for web host builder
`builder.UseServiceProviderFactory(new AutofacMultitenantServiceProviderFactory(ConfigureMultitenantContainer));`

```
public static MultitenantContainer ConfigureMultitenantContainer(IContainer container)
        {
            
            // This is the MULTITENANT PART. Set up your tenant-specific stuff here.
            var strategy = new ManualTenantIdentificationStrategy();
            var mtc = new MultitenantContainer(strategy, container);
            mtc.ConfigureTenant("a", cb => cb.RegisterType<TenantA>().As<ITenant>());
            return mtc;
        }

**Comment by junalmeida** [comment]
I will take a look on that, thanks for your suggestion

**Comment by junalmeida** [comment]
@ssunkari Syntax has changed and that may allow to inject a multitenant container. Let me know if that works for you.
