### ISSUE TITLE
Can you add support for both styles of services registration?

### ISSUE THREAD

**Issue by rafek1241** [junalmeida/autofac-azurefunctions#19]
In https://github.com/autofac/Autofac.Extensions.DependencyInjection we can do both:
```
  // ConfigureServices is where you register dependencies. This gets
  // called by the runtime before the ConfigureContainer method, below.
  public void ConfigureServices(IServiceCollection services)
  {
    // Add services to the collection. Don't build or return
    // any IServiceProvider or the ConfigureContainer method
    // won't get called.
    services.AddOptions();
  }

  // ConfigureContainer is where you can register things directly
  // with Autofac. This runs after ConfigureServices so the things
  // here will override registrations made in ConfigureServices.
  // Don't build the container; that gets done for you. If you
  // need a reference to the container, you need to use the
  // "Without ConfigureContainer" mechanism shown later.
  public void ConfigureContainer(ContainerBuilder builder)
  {
      builder.RegisterModule(new AutofacModule());
  }
```

In this application we can't do it. Can you provide such functionality? It would be easier to inject such extension in already existing projects.

**Comment by junalmeida** [comment]
Hi, thanks for supporting this project. If I understood correctly you want to be able to execute the `ConfigureServices` method. If that's the case, it is out of the scope of this project to make the magic happen automatically, however, you may do the same syntax with some code like:

``` 
    public override void Configure(IFunctionsHostBuilder builder)
    {
        ConfigureServices(builder.Services);
        builder
            // This is the required call in order to use autofac in your azure functions app
            .UseAutofacServiceProviderFactory(ConfigureContainer);
    }
    
  public void ConfigureServices(IServiceCollection services)
  {
    // Add services to the collection. Don't build or return
    // any IServiceProvider or the ConfigureContainer method
    // won't get called.
    services.AddOptions();
  }
```

**Comment by rafek1241** [comment]
@junalmeida 
I checked that and it was not working as you said that is why I have created this issue. Things that are registered in `IServiceCollection` not exists in autofac's container.

**Comment by junalmeida** [comment]
Do you have a project to show that? When you call the startup methods, internally it calls Populate just like in Autofac docs, so it should work. But since this is not an isolated environment, az func can change the service collection in the mean time.
