### ISSUE TITLE
`Autofac.*` prefix reservation for NuGet

### ISSUE THREAD

**Issue by tillig** [junalmeida/autofac-azurefunctions#21]
Hi! I'm one of the owners of [Autofac](https://github.com/autofac) and we recently [got an issue filed](https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/94) that's actually for the library homed in this repo. Admittedly we hadn't gone through [the process of dealing with NuGet prefix reservation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation) which is how you were able to post a package that _looks_ like it's an official Autofac package but isn't.

We're in the process of working through package ID reservation now. Since your package is already published you shouldn't be affected and should be able to continue publishing your package, but it won't have visual identifier in NuGet that the official Autofac packages have.

**I would like to ask, however, that you update your README to make it more obvious that this isn't an Autofac organization package.** For example, the phrasing "we have a documentation site" with the link to the Autofac docs implies that "we" - the owner of this package - is part of the overall Autofac org, which can be confusing to users coming looking for help. You also probably shouldn't direct folks to the Autofac discussion forum for help with this package since we can't support it there.

**It might also be good if you didn't use the Autofac logo on your package** to help more visually differentiate your package from official packages. Again, I'm less concerned with "intellectual property" than I am about getting the users the help they need with the packages they consume.

Anyway, thanks for the time, hoping we can work together to best get folks the tech they need and the assistance/support with that tech in the most efficient way possible.

**Comment by junalmeida** [comment]
Hello @tillig , thanks for letting me know, I will make changes as soon as I have some time. 
I have to mention that despite the "WE" wording at the very end of the readme, which is based on the readme of the library itself, it is mentioned before for the user that they need to `file issues and pull requests for this package in this repository rather than in the Autofac core repo.`

**Comment by tillig** [comment]
> it is mentioned before for the user that they need to `file issues and pull requests for this package in this repository`

True, and I did see that. It's just easy to miss (as evidenced by the issue we got for your library), hence the suggestion to hopefully make it _extra clear_, just in case folks skim over that or miss it. Thanks for the help here!

**Comment by junalmeida** [comment]
@tillig Yeah, and I'm agreeing with you. I just wanted to make it clear that was not my first intention. The "we" wording at the end is a mistake and I will fix it soon. I will mention you on the PR to fix this.

**Comment by tillig** [comment]
I just got notified by the NuGet admins that `Autofac.*` is now reserved. Again, you shouldn't have any issues continuing to publish your current package, but if you do, let me know and we'll see if we can unlock that part of the reservation for you.
