### ISSUE TITLE
Functions not registered

### ISSUE THREAD

**Issue by E-PressSend** [junalmeida/autofac-azurefunctions#25]
Hi Guys, 

I'd need your help to find out what is going wrong with my fucntion app.

This is my setup:

**Function App A** - Autofac configured using autofac-azurefunctions, everything works fine, not problem at all.
**Fucntion App B** - References **Function App A**, but only for some Service classes (No Functions are referenced). 
I tried to setup Autofac in the same way done for **Function App A**, but I keep getting the error when I call any of the Fucntion App (HTTP trigger in this case):

```
Autofac: The requested service 'PressSend.Snapzel.Payments.Functions.PaymentHooks' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
```

_PressSend.Snapzel.Payments.Functions.PaymentHooks_ is a Function App HTTP Trigger class.

This is the Startup class of **Fucntion App B**

```
public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.UseAutofacServiceProviderFactory(this.ConfigurePaymentsContainer);
             ....
        }

private void ConfigurePaymentsContainer(ContainerBuilder builder)
        {

            // Register all functions that resides in a given namespace
            // The function class itself will be created using autofac
            builder
                .RegisterAssemblyTypes(typeof(Startup).Assembly)
                .InNamespace("PressSend.Snapzel.Payments.Functions")
                .AsSelf() // Azure Functions core code resolves a function class by itself.
                .InstancePerTriggerRequest(); // This will scope nested dependencies to each function execution


            /*
              builder.RegisterType<PaymentHooks>()
            .AsSelf() // Azure Functions core code resolves a function class by itself.
            .InstancePerTriggerRequest(); // This will scope nested dependencies to each function execution
*/
        }
```

I tried registering the function app using RegisterAssemblyTypes and registering the single Functions one by one using RegisterType with no luck.

I feel like I making a big mistake somewhere but I don't see it.

Any suggestion?

Cheers

**Comment by E-PressSend** [comment]
Quick update.

It seems that the problem is caused by the reference to Function App A.

I tried to add     ```<FunctionsInDependencies>true</FunctionsInDependencies>``` to the project conf but it didn't make any difference.

Any suggestion on how to fix?

**Comment by junalmeida** [comment]
I believe that I'm going to need more information to try help you. First, tell me how your project structure looks like. So, `FunctionsInDependencies` is meant to be used by only one Function entry point (function App) with actual functions living on class libraries (the dependencies).

I am not sure what you mean by Function App A and Function App B. If those are two separate main entry points then I don't think `FunctionsInDependencies` makes sense to you. 

If you really need two main entry points (App A and App B) and both lives on the same solution and both depends on the same function, then add a third project - a class library, move the function to this class library, and then add it as a project reference to both Func A and Func B. On this use case, `FunctionsInDependencies` is required on both Func A and Func B entrypoints.
