### ISSUE TITLE
Services dont appear to be registered correctly?

### ISSUE THREAD

**Issue by waynebrantley** [junalmeida/autofac-azurefunctions#28]
We use a product called MassTransit with Autofac.  The registration appears to not work correctly.

Take a look at program.cs for how to reproduce.
https://github.com/twhitex/Sample-AzureFunction

Issue is - the same code works fine for registration when in a console or website (where we use autofacs code to connect the DI).

I am at a loss for what the issue is here!

**Comment by junalmeida** [comment]
I don't see in your csproj the reference to this library. Did you post the question on the wrong library?

**Comment by waynebrantley** [comment]
https://github.com/twhitex/Sample-AzureFunction/tree/rabbitmq
Sorry bad link!  it is in a branch

**Comment by junalmeida** [comment]
And what is the exception? Is there any stack trace? What does not work for you? 
Please provide more detail so I can try help you.

**Comment by waynebrantley** [comment]
This line - will fail with MassTransitOptions not found (not registered).
(Even though you can see the same resolution is found in the function)

var options = context.GetRequiredService<MassTransitOptions>();

If I register it with the Microsoft container it will resolve.  It is like we have two containers with the MassTransit registration.

This same style of registration and such (with autofac) works in non-function projects, so that is why I was thinking it was related to this library.

(the project you can just run and it will give the error)

**Comment by jvmlet** [comment]
My 2 cents: we are experiencing  similar behavior.
Looks like the  both MS DI and Autofac  containers are active, the one you get from `request.HttpContext.RequestServices` is `IServiceProvider` of MS DI's one.
So if you register services with Autofac, you can't resolve them from  `request.HttpContext.RequestServices`

**Comment by junalmeida** [comment]
Have you tried at:
https://github.com/twhitex/Sample-AzureFunction/blob/73302fc60f6bd3c448542d9a3b77da7fc1259dfd/src/Sample.AzureFunction/Startup.cs#L43

To Register it detailing the registration? I'm now sure of the defaults of AutoFac, but do you want it to be `AsSelf` or `AsImplementedInterfaces`? Do you want it to be `SingleInstance` or `IntancePerLifeTime` ?  

I also failed to find the exact place where you ask for an instance. I don't see the parameter `MassTransitOptions` on any constructor, neither a call to `ILifeTimeScope.Resolve<MassTransitOptions>()`.

**Comment by jvmlet** [comment]
@junalmeida it's here https://github.com/twhitex/Sample-AzureFunction/blob/73302fc60f6bd3c448542d9a3b77da7fc1259dfd/src/Sample.AzureFunction/Startup.cs#L25

**Comment by junalmeida** [comment]
`GetRequiredServices` is not an autofac registration method AFAIK, unless I am missing something.

**Comment by jvmlet** [comment]
You are right. It's not autofac's native query method, but after you registered Auitofac as service provider factory using `UseAutofacServiceProviderFactory`, the `IServiceProvider` implementation should see the registrations performed on Autofac's container builder.

**Comment by jvmlet** [comment]
I think you are missing `Populate` call on Autofac's container to copy registrations from MS DI service collection

**Comment by waynebrantley** [comment]
There is a populate call in the code called by UseAutofacServiceProviderFactory
https://github.com/junalmeida/autofac-azurefunctions/blob/master/Autofac.Extensions.DependencyInjection.AzureFunctions/ConfigurationExtensions.cs#L50

The MassTransit registration cannot resolve anything registered by autofac.  
On non function apps, an IServiceProviderFactory is created and then added into the normal DI.
I am not sure if that works in function or not - but possibly the populate above is called too early, etc.  If we create an IServiceProviderFactory and return that - which will theoretically call build when it is ready - at which point we an call the users code on the builder as well as populate, etc.   

Something like this?
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/DependencyInjection/WebHostServiceProviderFactory.cs

**Comment by junalmeida** [comment]
@jvmlet Not entirely true. The Autofac is not replaced on the Functions inner code, only during Function execution. So, if you add the class/interface on a function constructor it should work. Anything else is an unexpected scenario.

**Comment by jvmlet** [comment]
So, for example. with `[HttpTrigger]`  , I'm getting `request` object with has `request.HttpContext.RequestServices` **native** DI container, not `Autofac`, right ?

**Comment by junalmeida** [comment]
@jvmlet Yes, correct. `RequestServices` is the native DI container, not Autofac. However you may get Autofac by requesting `ILifetimeScope` from either `RequestServices` or the function class constructor.
