### ISSUE TITLE
Any plans to support the isolated model?

### ISSUE THREAD

**Issue by IanKemp** [junalmeida/autofac-azurefunctions#31]
Or is this package not required in the isolated model?

**Comment by junalmeida** [comment]
I'm yet to port current functions to the new isolated model, but since it is isolated, I don't think it will be needed. It is based off the HostBuilder, so you probably only need a startup code similar to this:

``` 
new HostBuilder()
    .UseServiceProviderFactory(new AutofacServiceProviderFactory())
```

**Comment by fowl2** [comment]
I guess it'd want a `IFunctionActivator` implementation?

eg. https://github.com/WestDiscGolf/AutofacAndAzureFunctions/blob/main/src/Api/Program.cs

see https://github.com/Azure/azure-functions-dotnet-worker/issues/716

(And maybe a `RegistrationSource`?)
